"""Canonical NFL Roster & Team Verification Module.

Enforces real-world NFL franchise assignments for all players, preventing
simulation artifacts, swapped team tags, and erroneous inclusions of players
who already played on Thursday Night or play in non-slate island games.
"""

from typing import Any
import pandas as pd

CANONICAL_REAL_TEAMS: dict[str, str] = {
    # QBs
    "Lamar Jackson": "BAL",
    "Jalen Hurts": "PHI",
    "Caleb Williams": "CHI",
    "Joe Burrow": "CIN",
    "Brock Purdy": "SF",
    "Dak Prescott": "DAL",
    "Jayden Daniels": "WAS",
    "Trevor Lawrence": "JAC",
    "Jordan Love": "GB",
    "Baker Mayfield": "TB",
    "Drake Maye": "NE",
    "Justin Herbert": "LAC",
    "Bo Nix": "DEN",
    "Bryce Young": "CAR",
    "C.J. Stroud": "HOU",
    "Aaron Rodgers": "NYJ",
    "Kyler Murray": "ARI",
    "Tua Tagovailoa": "MIA",
    "Sam Darnold": "MIN",
    "Kirk Cousins": "ATL",
    "Geno Smith": "SEA",
    "Deshaun Watson": "CLE",
    "Jacoby Brissett": "NE",
    "Drew Lock": "SEA",
    "Cooper Rush": "DAL",
    "Carson Wentz": "KC",
    "Kenny Pickett": "PHI",
    "Mac Jones": "JAC",
    "Gardner Minshew II": "LV",
    "Gardner Minshew": "LV",
    "Aidan O'Connell": "LV",
    "Sam Howell": "SEA",
    "Zach Wilson": "DEN",
    "Jarrett Stidham": "DEN",
    "Mason Rudolph": "TEN",
    "Davis Mills": "HOU",
    "Joe Flacco": "IND",
    "Nick Mullens": "MIN",
    "Marcus Mariota": "WAS",
    "Mitchell Trubisky": "BUF",
    "Andy Dalton": "CAR",
    "Spencer Rattler": "NO",
    "J.J. McCarthy": "MIN",
    "Michael Penix Jr.": "ATL",
    "Patrick Mahomes": "KC",
    "Josh Allen": "BUF",
    "Jared Goff": "DET",
    "Matthew Stafford": "LAR",
    "Daniel Jones": "NYG",
    "Anthony Richardson": "IND",

    # RBs
    "Christian McCaffrey": "SF",
    "Bijan Robinson": "ATL",
    "Derrick Henry": "BAL",
    "Saquon Barkley": "PHI",
    "De'Von Achane": "MIA",
    "Bucky Irving": "TB",
    "Ashton Jeanty": "LV",
    "Chase Brown": "CIN",
    "Javonte Williams": "DEN",
    "Omarion Hampton": "LAC",
    "Breece Hall": "NYJ",
    "D'Andre Swift": "CHI",
    "David Montgomery": "DET",
    "Jahmyr Gibbs": "DET",
    "James Cook": "BUF",
    "Jonathan Taylor": "IND",
    "Isiah Pacheco": "KC",
    "Kyren Williams": "LAR",
    "Devin Singletary": "NYG",
    "Tyrone Tracy Jr.": "NYG",
    "Travis Etienne Jr.": "JAX",
    "Travis Etienne": "JAX",
    "Rhamondre Stevenson": "NE",
    "Chuba Hubbard": "CAR",
    "J.K. Dobbins": "LAC",
    "Jaylen Warren": "PIT",
    "MarShawn Lloyd": "GB",
    "Aaron Jones Sr.": "MIN",
    "Aaron Jones": "MIN",
    "Kyle Monangai": "CHI",
    "Tony Pollard": "TEN",
    "Tyjae Spears": "TEN",
    "Tyler Allgeier": "ATL",
    "Rico Dowdle": "DAL",
    "Jordan Mason": "SF",
    "Ezekiel Elliott": "DAL",
    "Najee Harris": "PIT",
    "Rachaad White": "TB",
    "Jerome Ford": "CLE",
    "Nick Chubb": "CLE",
    "Brian Robinson Jr.": "WAS",
    "Austin Ekeler": "WAS",
    "James Conner": "ARI",
    "Trey Benson": "ARI",
    "Raheem Mostert": "MIA",
    "Jaylen Wright": "MIA",
    "Kenneth Walker III": "SEA",
    "Kenneth Walker": "SEA",
    "Zach Charbonnet": "SEA",
    "Gus Edwards": "LAC",
    "Kimani Vidal": "LAC",
    "Zamir White": "LV",
    "Alexander Mattison": "LV",
    "Alvin Kamara": "NO",
    "Jamaal Williams": "NO",
    "Kendre Miller": "NO",
    "Tank Bigsby": "JAX",
    "Miles Sanders": "CAR",
    "Jonathon Brooks": "CAR",
    "Antonio Gibson": "NE",
    "Cam Akers": "MIN",
    "Dameon Pierce": "HOU",
    "Joe Mixon": "HOU",
    "Ty Chandler": "MIN",
    "Roschon Johnson": "CHI",
    "Emanuel Wilson": "GB",
    "Braelon Allen": "NYJ",
    "Ray Davis": "BUF",
    "Blake Corum": "LAR",
    "Trey Sermon": "IND",
    "Carson Steele": "KC",
    "Kareem Hunt": "KC",
    "Cam Skattebo": "NYG",

    # WRs
    "Jaxon Smith-Njigba": "SEA",
    "Ja'Marr Chase": "CIN",
    "Justin Jefferson": "MIN",
    "CeeDee Lamb": "DAL",
    "Mike Evans": "TB",
    "George Pickens": "PIT",
    "Chris Olave": "NO",
    "Nico Collins": "HOU",
    "Drake London": "ATL",
    "Zay Flowers": "BAL",
    "DeVonta Smith": "PHI",
    "A.J. Brown": "PHI",
    "Garrett Wilson": "NYJ",
    "Tee Higgins": "CIN",
    "DK Metcalf": "SEA",
    "Christian Watson": "GB",
    "Jaylen Waddle": "MIA",
    "Tyreek Hill": "MIA",
    "Ladd McConkey": "LAC",
    "Rome Odunze": "CHI",
    "Keenan Allen": "CHI",
    "DJ Moore": "CHI",
    "Deebo Samuel Sr.": "SF",
    "Deebo Samuel": "SF",
    "Brandon Aiyuk": "SF",
    "Courtland Sutton": "DEN",
    "Stefon Diggs": "HOU",
    "Tank Dell": "HOU",
    "Terry McLaurin": "WAS",
    "Michael Pittman Jr.": "IND",
    "Michael Pittman": "IND",
    "Josh Downs": "IND",
    "Alec Pierce": "IND",
    "AD Mitchell": "IND",
    "Adonai Mitchell": "IND",
    "Rashee Rice": "KC",
    "Xavier Worthy": "KC",
    "Hollywood Brown": "KC",
    "Marquise Brown": "KC",
    "JuJu Smith-Schuster": "KC",
    "Puka Nacua": "LAR",
    "Cooper Kupp": "LAR",
    "Demarcus Robinson": "LAR",
    "Jordan Whittington": "LAR",
    "Tutu Atwell": "LAR",
    "Malik Nabers": "NYG",
    "Wan'Dale Robinson": "NYG",
    "Darius Slayton": "NYG",
    "Jalin Hyatt": "NYG",
    "Amon-Ra St. Brown": "DET",
    "Jameson Williams": "DET",
    "Tim Patrick": "DET",
    "Kalif Raymond": "DET",
    "Khalil Shakir": "BUF",
    "Keon Coleman": "BUF",
    "Curtis Samuel": "BUF",
    "Mack Hollins": "BUF",
    "Marquez Valdes-Scantling": "BUF",
    "Romeo Doubs": "GB",
    "Jayden Reed": "GB",
    "Dontayvion Wicks": "GB",
    "Jordan Addison": "MIN",
    "Jalen Nailor": "MIN",
    "Chris Godwin Jr.": "TB",
    "Chris Godwin": "TB",
    "Jalen McMillan": "TB",
    "Quentin Johnston": "LAC",
    "Joshua Palmer": "LAC",
    "Marvin Harrison Jr.": "ARI",
    "Michael Wilson": "ARI",
    "Greg Dortch": "ARI",
    "Brian Thomas Jr.": "JAX",
    "Christian Kirk": "JAX",
    "Gabe Davis": "JAX",
    "Parker Washington": "JAX",
    "Jauan Jennings": "SF",
    "Ricky Pearsall": "SF",
    "Malik Washington": "MIA",
    "Odell Beckham Jr.": "MIA",
    "Devaughn Vele": "DEN",
    "Josh Reynolds": "DEN",
    "Marvin Mims Jr.": "DEN",
    "Troy Franklin": "DEN",
    "Jakobi Meyers": "LV",
    "Tre Tucker": "LV",
    "Rashid Shaheed": "NO",
    "Calvin Ridley": "TEN",
    "DeAndre Hopkins": "TEN",
    "Tyler Boyd": "TEN",
    "Nick Westbrook-Ikhine": "TEN",
    "Diontae Johnson": "CAR",
    "Adam Thielen": "CAR",
    "Xavier Legette": "CAR",
    "Jalen Coker": "CAR",
    "Jerry Jeudy": "CLE",
    "Amari Cooper": "CLE",
    "Elijah Moore": "CLE",
    "Cedric Tillman": "CLE",
    "Tyler Lockett": "SEA",
    "Demario Douglas": "NE",
    "Kendrick Bourne": "NE",
    "Ja'Lynn Polk": "NE",
    "K.J. Osborn": "NE",
    "Calvin Austin III": "PIT",
    "Van Jefferson": "PIT",
    "Roman Wilson": "PIT",
    "Luke McCaffrey": "WAS",
    "Dyami Brown": "WAS",
    "Noah Brown": "WAS",
    "Brandin Cooks": "DAL",
    "Jalen Tolbert": "DAL",
    "KaVontae Turpin": "DAL",
    "Rashod Bateman": "BAL",
    "Nelson Agholor": "BAL",
    "Devontez Walker": "BAL",
    "Tylan Wallace": "BAL",
    "Andrei Iosivas": "CIN",
    "Trenton Irwin": "CIN",
    "Jermaine Burton": "CIN",
    "Darnell Mooney": "ATL",
    "Ray-Ray McCloud": "ATL",
    "KhaDarel Hodge": "ATL",
    "Casey Washington": "ATL",
    "Allen Lazard": "NYJ",
    "Mike Williams": "NYJ",
    "Malachi Corley": "NYJ",
    "Xavier Gipson": "NYJ",

    # TEs
    "Trey McBride": "ARI",
    "Brock Bowers": "LV",
    "Tucker Kraft": "GB",
    "Luke Musgrave": "GB",
    "George Kittle": "SF",
    "Dallas Goedert": "PHI",
    "Juwan Johnson": "NO",
    "Taysom Hill": "NO",
    "Foster Moreau": "NO",
    "Dalton Kincaid": "BUF",
    "Dawson Knox": "BUF",
    "Sam LaPorta": "DET",
    "Brock Wright": "DET",
    "Travis Kelce": "KC",
    "Noah Gray": "KC",
    "Colby Parkinson": "LAR",
    "Davis Allen": "LAR",
    "Theo Johnson": "NYG",
    "Daniel Bellinger": "NYG",
    "Kylen Granson": "IND",
    "Mo Alie-Cox": "IND",
    "Drew Ogletree": "IND",
    "Jake Ferguson": "DAL",
    "Luke Schoonmaker": "DAL",
    "Zach Ertz": "WAS",
    "Ben Sinnott": "WAS",
    "John Bates": "WAS",
    "Chig Okonkwo": "TEN",
    "Chigoziem Okonkwo": "TEN",
    "Josh Whyle": "TEN",
    "Nick Vannett": "TEN",
    "David Njoku": "CLE",
    "Jordan Akins": "CLE",
    "Cade Otton": "TB",
    "Payne Durham": "TB",
    "Hunter Henry": "NE",
    "Austin Hooper": "NE",
    "Pat Freiermuth": "PIT",
    "Darnell Washington": "PIT",
    "Connor Heyward": "PIT",
    "Mark Andrews": "BAL",
    "Isaiah Likely": "BAL",
    "Charlie Kolar": "BAL",
    "Mike Gesicki": "CIN",
    "Drew Sample": "CIN",
    "Tanner Hudson": "CIN",
    "Erick All": "CIN",
    "Dalton Schultz": "HOU",
    "Cade Stover": "HOU",
    "Brevin Jordan": "HOU",
    "Evan Engram": "JAX",
    "Brenton Strange": "JAX",
    "Luke Farrell": "JAX",
    "Greg Dulcich": "DEN",
    "Adam Trautman": "DEN",
    "Nate Adkins": "DEN",
    "Hayden Hurst": "LAC",
    "Will Dissly": "LAC",
    "Stone Smartt": "LAC",
    "Michael Mayer": "LV",
    "Harrison Bryant": "LV",
    "Noah Fant": "SEA",
    "AJ Barner": "SEA",
    "Pharaoh Brown": "SEA",
    "Tip Reiman": "ARI",
    "Elijah Higgins": "ARI",
    "Jonnu Smith": "MIA",
    "Durham Smythe": "MIA",
    "Julian Hill": "MIA",
    "Eric Saubert": "SF",
    "Tommy Tremble": "CAR",
    "Ja'Tavion Sanders": "CAR",
    "Ian Thomas": "CAR",
    "Kyle Pitts": "ATL",
    "Charlie Woerner": "ATL",
    "Tyler Conklin": "NYJ",
    "Jeremy Ruckert": "NYJ",
    "Cole Kmet": "CHI",
    "Gerald Everett": "CHI",
    "T.J. Hockenson": "MIN",
    "Josh Oliver": "MIN",
    "Johnny Mundt": "MIN",
}

CANONICAL_TEAM_ALIASES: dict[str, list[str]] = {
    "WSH": ["WAS"],
    "WAS": ["WSH"],
    "JAX": ["JAC"],
    "JAC": ["JAX"],
    "LV": ["LVR", "OAK"],
    "LVR": ["LV", "OAK"],
    "TB": ["TBB"],
    "TBB": ["TB"],
    "NO": ["NOS"],
    "NOS": ["NO"],
    "SF": ["SFO"],
    "SFO": ["SF"],
    "GB": ["GBP"],
    "GBP": ["GB"],
    "KC": ["KCC"],
    "KCC": ["KC"],
    "NE": ["NEP"],
    "NEP": ["NE"],
    "LAR": ["LA", "STL"],
    "LA": ["LAR", "STL"],
}

TEAM_ALIASES: dict[str, str] = {
    "JAC": "JAX",
    "WAS": "WSH",
    "LVR": "LV",
    "TBB": "TB",
    "NOS": "NO",
    "SFO": "SF",
    "GBP": "GB",
    "KCC": "KC",
    "NEP": "NE",
    "LA": "LAR",
}


def resolve_team_alias(team: str, available_teams: Any) -> str | None:
    """Finds the matching team code within available_teams, checking aliases."""
    if not team:
        return None
    t_clean = str(team).upper().strip()
    if t_clean in available_teams:
        return t_clean
    for alias in CANONICAL_TEAM_ALIASES.get(t_clean, []):
        if alias in available_teams:
            return alias
    return None


def normalize_roster_dataframe(
    df: pd.DataFrame,
    team_vegas_schedule: dict[str, dict[str, Any]] | None = None,
    filter_non_slate: bool = True,
) -> pd.DataFrame:
    """Normalizes player team/opponent/game columns against real NFL teams.

    If team_vegas_schedule is provided, drops players whose real teams are not
    playing in the active slate games (e.g. Thursday TNF, Sunday Night SNF, Monday Night MNF).
    """
    rows_to_keep = []
    for _, row in df.iterrows():
        raw_name = row.get("Nickname")
        if pd.isna(raw_name) or not str(raw_name).strip():
            raw_name = f"{row.get('First Name', '')} {row.get('Last Name', '')}".strip()
        name = str(raw_name).strip()
        orig_team = str(row.get("Team", "")).strip().upper()

        real_team = CANONICAL_REAL_TEAMS.get(name, orig_team)

        if team_vegas_schedule:
            # Match real_team or its alias in schedule
            matched_sched_team = resolve_team_alias(real_team, team_vegas_schedule)
            if not matched_sched_team:
                matched_sched_team = resolve_team_alias(orig_team, team_vegas_schedule)

            # If player's real team is not in the active slate schedule, drop
            if filter_non_slate and not matched_sched_team:
                continue

            if matched_sched_team:
                game_ctx = team_vegas_schedule[matched_sched_team]
                row["Team"] = matched_sched_team
                row["Opponent"] = game_ctx.get("opponent", row.get("Opponent"))
                row["Game"] = game_ctx.get("game", row.get("Game"))
            else:
                row["Team"] = real_team
        else:
            row["Team"] = real_team

        rows_to_keep.append(row)

    return pd.DataFrame(rows_to_keep)

