import React, { useState } from 'react'
import type { OptimizedLineupResult, LeagueSummaryResponse, SlotAssignment } from '../../types'
import { NFLTeamLogo } from '../shared/NFLTeamLogo'

interface ShareLineupModalProps {
  isOpen: boolean
  onClose: () => void
  lineup: OptimizedLineupResult | null
  league: LeagueSummaryResponse | null
  strategyMode: string
  projectionSource: string
}

export const ShareLineupModal: React.FC<ShareLineupModalProps> = ({
  isOpen,
  onClose,
  lineup,
  league,
  strategyMode,
  projectionSource,
}) => {
  const [copied, setCopied] = useState(false)

  if (!isOpen || !lineup) return null

  const startersTotal = lineup.starters.reduce(
    (sum: number, s: SlotAssignment) => sum + s.recommended_player.projected_points,
    0
  )

  const generateMarkdown = () => {
    const week = league?.current_week ?? 1
    const leagueName = league?.name ?? 'Fantasy League'
    let text = `🏈 **${leagueName.toUpperCase()} — WEEK ${week} OPTIMAL LINEUP**\n`
    text += `⚡ Total Projection: **${startersTotal.toFixed(1)} pts** | Strategy: *${strategyMode}* | Source: *${projectionSource}*\n`
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`

    lineup.starters.forEach((slot: SlotAssignment) => {
      const p = slot.recommended_player
      const dvpRank = p.opp_dvp_rank ? ` • DvP #${p.opp_dvp_rank}` : ''
      const vs = p.is_home ? 'vs' : '@'
      text += `**${slot.slot_name}**: ${p.full_name} (${p.pro_team} ${vs} ${p.opponent}) — **${p.projected_points.toFixed(1)} pts**${dvpRank}\n`
    })

    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`
    text += `Generated by Apex Fantasy Quant Engine\n`
    return text
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdown())
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      // Fallback
    }
  }

  return (
    <div className="share-modal-backdrop" onClick={onClose}>
      <div className="share-modal-card" onClick={(e) => e.stopPropagation()}>
        <div className="share-modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span style={{ fontSize: '24px' }}>📤</span>
            <div>
              <h3 className="share-modal-title">Export & Share Lineup Card</h3>
              <p className="share-modal-subtitle">
                {league?.name || 'League'} • Week {league?.current_week || 1} • {startersTotal.toFixed(1)} Projected Pts
              </p>
            </div>
          </div>
          <button className="share-modal-close" onClick={onClose}>✕</button>
        </div>

        {/* Visual Lineup Card */}
        <div className="share-lineup-preview">
          <div className="share-card-banner">
            <div className="share-banner-brand">
              <span className="share-brand-text">APEX QUANT MODEL</span>
              <span className="pill cyan" style={{ fontSize: '10px', padding: '1px 6px' }}>
                {strategyMode}
              </span>
            </div>
            <div className="share-banner-score tabular-nums">
              {startersTotal.toFixed(1)} <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>PTS</span>
            </div>
          </div>

          <div className="share-slots-grid">
            {lineup.starters.map((slot, idx) => {
              const p = slot.recommended_player
              return (
                <div key={idx} className="share-slot-row">
                  <div className="share-slot-pos-badge">{slot.slot_name}</div>
                  <NFLTeamLogo team={p.pro_team} size={18} />
                  <div className="share-slot-name-col">
                    <span className="share-slot-player-name">{p.full_name}</span>
                    <span className="share-slot-matchup-text">
                      {p.pro_team} {p.is_home ? 'vs' : '@'} {p.opponent}
                    </span>
                  </div>
                  <div className="share-slot-pts tabular-nums">
                    {p.projected_points.toFixed(1)}
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Copy actions */}
        <div className="share-modal-actions">
          <button
            className={`share-copy-btn ${copied ? 'copied' : ''}`}
            onClick={handleCopy}
          >
            {copied ? '✓ Copied to Clipboard!' : '📋 Copy for Discord / Sleeper'}
          </button>
          <button className="share-dismiss-btn" onClick={onClose}>
            Done
          </button>
        </div>
      </div>
    </div>
  )
}
